[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "myproject"
version = "0.0.1"
dependencies = [
    "torch==2.2.2",
    "pandas==2.0.3",
    "numpy==1.24.4"
]
requires-python = "==3.8"
